import { Mission } from '../../types/game';

export const STORY_MISSIONS: Mission[] = [
  {
    id: 'ch1_first_patrol',
    chapter: 1,
    title: 'Chapter 1: Rookie — First Patrol',
    subtitle: 'Street Gang Disturbance',
    description: 'Dispatch reports syndicate thugs harassing pedestrians near the commercial plaza alley. Move in, neutralize the threat, and arrest or take down the suspects.',
    mode: 'story',
    rewardMoney: 450,
    rewardXP: 300,
    requiredRank: 1,
    unlocked: true,
    completed: false,
    objectives: [
      {
        id: 'obj_1',
        description: 'Patrol to the commercial alleyway',
        targetType: 'reach',
        targetPos: { x: -28, y: 0, z: -20 },
        currentCount: 0,
        requiredCount: 1,
        isCompleted: false,
      },
      {
        id: 'obj_2',
        description: 'Neutralize or arrest 3 street thugs',
        targetType: 'kill',
        currentCount: 0,
        requiredCount: 3,
        isCompleted: false,
      },
    ],
    dialogueIntro: [
      'Dispatch: "Unit 24, Officer Carter. We have reports of armed gang activity near Sector 4."',
      'Alex Carter: "10-4 Dispatch. Rolling to the scene now. Will assess and intervene."',
    ],
    dialogueOutro: [
      'Alex Carter: "Dispatch, suspects neutralized. Alley secured. Found coded syndicate tags on the wall."',
      'Dispatch: "Copy that, Officer. Good work. Head to headquarters for debrief."',
    ],
  },
  {
    id: 'ch2_warehouse_bust',
    chapter: 2,
    title: 'Chapter 2: The Contraband Warehouse',
    subtitle: 'Industrial Infiltration',
    description: 'Intelligence indicates a major arms cache and illicit goods stockpile at the east harbor warehouse. Breach the perimeter and recover the contraband.',
    mode: 'story',
    rewardMoney: 950,
    rewardXP: 600,
    requiredRank: 1,
    unlocked: false,
    completed: false,
    objectives: [
      {
        id: 'obj_reach_wh',
        description: 'Infiltrate the Industrial Warehouse',
        targetType: 'reach',
        targetPos: { x: 45, y: 0, z: 35 },
        currentCount: 0,
        requiredCount: 1,
        isCompleted: false,
      },
      {
        id: 'obj_defeat_guards',
        description: 'Defeat syndicate enforcers defending the warehouse',
        targetType: 'kill',
        currentCount: 0,
        requiredCount: 4,
        isCompleted: false,
      },
    ],
    dialogueIntro: [
      'Captain Miller: "Carter, this warehouse supplies every crew in the district. Expect heavy resistance."',
      'Alex Carter: "Understood, Captain. Going in hot."',
    ],
    dialogueOutro: [
      'Alex Carter: "Warehouse cleared. Recovered crate of illegal military ordnance bearing Viper Vance\'s insignia."',
      'Captain Miller: "Outstanding job, Carter. You just dealt a severe blow to their distribution network."',
    ],
  },
  {
    id: 'ch3_highway_pursuit',
    chapter: 3,
    title: 'Chapter 3: The Highway Chase',
    subtitle: 'High-Speed Syndicate Pursuit',
    description: 'A black syndicate getaway muscle car has fled the scene at high speed! Get into your police cruiser, turn on the sirens, and disable the suspect vehicle!',
    mode: 'chase',
    rewardMoney: 1500,
    rewardXP: 900,
    requiredRank: 2,
    unlocked: false,
    completed: false,
    objectives: [
      {
        id: 'obj_enter_car',
        description: 'Enter your Police Cruiser and turn on emergency sirens',
        targetType: 'reach',
        targetPos: { x: -25, y: 0, z: 28 },
        currentCount: 0,
        requiredCount: 1,
        isCompleted: false,
      },
      {
        id: 'obj_stop_car',
        description: 'Chase down and disable the Syndicate Getaway Vehicle',
        targetType: 'chase_stop',
        currentCount: 0,
        requiredCount: 1,
        isCompleted: false,
      },
    ],
    dialogueIntro: [
      'Dispatch: "ALL UNITS: Suspect vehicle is a modified black muscle car speeding through Downtown!"',
      'Alex Carter: "In pursuit! Sirens engaged, executing pit maneuver!"',
    ],
    dialogueOutro: [
      'Alex Carter: "Suspect vehicle disabled! Suspect in custody. Requesting transport tow."',
      'Dispatch: "Suspect vehicle secured, stellar driving Officer Carter!"',
    ],
  },
  {
    id: 'ch4_bank_hostage',
    chapter: 4,
    title: 'Chapter 4: Bank Hostage Rescue',
    subtitle: 'Metro Bank Siege',
    description: 'Syndicate enforcers have breached Metro Bank and taken innocent civilians hostage. Exercise extreme caution: eliminate the hostage takers without civilian casualties!',
    mode: 'story',
    rewardMoney: 2200,
    rewardXP: 1400,
    requiredRank: 3,
    unlocked: false,
    completed: false,
    objectives: [
      {
        id: 'obj_reach_bank',
        description: 'Approach Metro Bank plaza',
        targetType: 'reach',
        targetPos: { x: 45, y: 0, z: -35 },
        currentCount: 0,
        requiredCount: 1,
        isCompleted: false,
      },
      {
        id: 'obj_clear_bank',
        description: 'Neutralize the 4 bank raiders',
        targetType: 'kill',
        currentCount: 0,
        requiredCount: 4,
        isCompleted: false,
      },
    ],
    dialogueIntro: [
      'Alex Carter: "Dispatch, arriving at Metro Bank. Perimeters compromised, hostiles armed inside."',
      'SWAT Lead: "You have green light for tactical entry, Carter. Protect the hostages at all costs."',
    ],
    dialogueOutro: [
      'Alex Carter: "Hostiles down, bank vault secure, all civilians safely evacuated!"',
      'Mayor: "Officer Carter, the entire city owes you a debt of gratitude today."',
    ],
  },
  {
    id: 'ch5_viper_showdown',
    chapter: 5,
    title: 'Chapter 5: Final Showdown — Viper Vance',
    subtitle: 'Harbor Stronghold Boss Fight',
    description: 'The head of the criminal syndicate, "Viper" Vance, has been cornered at his private harbor compound. He is heavily armed with bodyguards and military equipment.',
    mode: 'story',
    rewardMoney: 5000,
    rewardXP: 2500,
    requiredRank: 4,
    unlocked: false,
    completed: false,
    objectives: [
      {
        id: 'obj_boss',
        description: 'Defeat Syndicate Kingpin "Viper" Vance',
        targetType: 'kill',
        targetPos: { x: 65, y: 0, z: 65 },
        currentCount: 0,
        requiredCount: 1,
        isCompleted: false,
      },
    ],
    dialogueIntro: [
      'Viper Vance: "You think a rookie cop can dismantle my empire, Carter? You won\'t leave this harbor alive!"',
      'Alex Carter: "Your run is over, Vance. Step away from the weapon or get taken down."',
    ],
    dialogueOutro: [
      'Alex Carter: "Viper Vance has been neutralized. The city syndicate is broken."',
      'Police Chief: "Officer Alex Carter, for extraordinary heroism, you are promoted to Detective Sergeant!"',
    ],
  },
];
