import { WeaponConfig } from '../../types/game';

export const INITIAL_WEAPONS: WeaponConfig[] = [
  {
    id: 'vortex9',
    name: 'Vortex-9 Service Pistol',
    category: 'handgun',
    damage: 26,
    fireRate: 4.5,
    magazineSize: 15,
    currentAmmo: 15,
    reserveAmmo: 90,
    reloadTime: 1.4,
    range: 45,
    spread: 0.03,
    isAutomatic: false,
    unlocked: true,
    price: 0,
    upgradeLevel: 1,
  },
  {
    id: 'specter45',
    name: 'Specter-45 Tactical SMG',
    category: 'smg',
    damage: 20,
    fireRate: 11,
    magazineSize: 30,
    currentAmmo: 30,
    reserveAmmo: 150,
    reloadTime: 1.8,
    range: 40,
    spread: 0.06,
    isAutomatic: true,
    unlocked: true,
    price: 600,
    upgradeLevel: 1,
  },
  {
    id: 'apex12',
    name: 'Apex-12 Breacher Shotgun',
    category: 'shotgun',
    damage: 65,
    fireRate: 1.6,
    magazineSize: 8,
    currentAmmo: 8,
    reserveAmmo: 40,
    reloadTime: 2.4,
    range: 22,
    spread: 0.12,
    isAutomatic: false,
    unlocked: false,
    price: 1200,
    upgradeLevel: 1,
  },
  {
    id: 'titan_ar',
    name: 'Titan-AR Assault Rifle',
    category: 'rifle',
    damage: 34,
    fireRate: 8,
    magazineSize: 30,
    currentAmmo: 30,
    reserveAmmo: 120,
    reloadTime: 2.1,
    range: 65,
    spread: 0.04,
    isAutomatic: true,
    unlocked: false,
    price: 2400,
    upgradeLevel: 1,
  },
  {
    id: 'pulse_taser',
    name: 'Pulse-Taser Non-Lethal',
    category: 'taser',
    damage: 10,
    fireRate: 2,
    magazineSize: 4,
    currentAmmo: 4,
    reserveAmmo: 20,
    reloadTime: 1.5,
    range: 18,
    spread: 0.02,
    isAutomatic: false,
    unlocked: true,
    price: 0,
    upgradeLevel: 1,
    isNonLethal: true,
  },
];
